### ISSUE TITLE
Недостаточно аргументов в реализации метода обработчика ошибок

### ISSUE THREAD

**Issue by plasticfiresam** [surfstudio/surf-flutter-app-template#15]
https://github.com/surfstudio/surf-flutter-app-template/blob/49282c90c62bdcf773e44cb75b15ac7c245c6350/lib/util/default_error_handler.dart#L7
<img width="600" alt="Screen Shot 2022-08-15 at 08 09 35" src="https://user-images.githubusercontent.com/22907144/184562327-07ba734f-11cd-449a-8ef4-1494e15dde44.png">

В реализации метода обработчика ошибок нужен необязательный аргумент: StackTrace? stackTrace, в шаблонном проекте и примере на основе шаблона он не указан.

```
@override
  void handleError(Object error, {StackTrace? stackTrace}) {
    // ignore: avoid_print
    print(error);
  }
```

**Comment by plasticfiresam** [comment]
Судя по всему, из-за того что версия пакета в шаблоне не зафиксирована, у меня прилетела новая версия, которая прокидывает этот аргумент
https://pub.dev/packages/elementary/changelog#140

**Comment by dshevchenkoo** [comment]
Поправили в рамках https://github.com/surfstudio/surf-flutter-app-template/pull/16
